# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawRewardsClient, RawRewardsClient
from .types.create_rewards_request_reward import CreateRewardsRequestReward
from .types.create_rewards_response import CreateRewardsResponse
from .types.get_rewards_response import GetRewardsResponse
from .types.list_rewards_response_item import ListRewardsResponseItem
from .types.update_rewards_request_reward import UpdateRewardsRequestReward
from .types.update_rewards_response import UpdateRewardsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RewardsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRewardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRewardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRewardsClient
        """
        return self._raw_client

    def list(
        self,
        account_id: int,
        *,
        card_id: typing.Optional[int] = None,
        active: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ListRewardsResponseItem]:
        """
        Returns all rewards for the store. Optionally filter by card or active status.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        card_id : typing.Optional[int]
            Filter rewards belonging to a specific card

        active : typing.Optional[str]
            When present, return only active rewards

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListRewardsResponseItem]
            An array of reward objects

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.rewards.list(
            account_id=1,
        )
        """
        _response = self._raw_client.list(account_id, card_id=card_id, active=active, request_options=request_options)
        return _response.data

    def create(
        self,
        account_id: int,
        *,
        reward: CreateRewardsRequestReward,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateRewardsResponse:
        """
        Creates a new reward for a loyalty card. The card must belong to the same store.
        The `card_id` is required on create but cannot be changed afterwards.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        reward : CreateRewardsRequestReward

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateRewardsResponse
            The newly created reward object

        Examples
        --------
        from leal import Leal
        from leal.rewards import CreateRewardsRequestReward

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.rewards.create(
            account_id=1,
            reward=CreateRewardsRequestReward(
                card_id=1,
                name="name",
                stamps_required=1,
            ),
        )
        """
        _response = self._raw_client.create(account_id, reward=reward, request_options=request_options)
        return _response.data

    def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetRewardsResponse:
        """
        Returns a single reward by ID.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Reward ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetRewardsResponse
            A reward object

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.rewards.get(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.get(account_id, id, request_options=request_options)
        return _response.data

    def delete(self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes a reward. This cannot be undone.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Reward ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.rewards.delete(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.delete(account_id, id, request_options=request_options)
        return _response.data

    def update(
        self,
        account_id: int,
        id: int,
        *,
        reward: UpdateRewardsRequestReward,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateRewardsResponse:
        """
        Updates an existing reward. The `card_id` cannot be changed after creation.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Reward ID

        reward : UpdateRewardsRequestReward

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateRewardsResponse
            The updated reward object

        Examples
        --------
        from leal import Leal
        from leal.rewards import UpdateRewardsRequestReward

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.rewards.update(
            account_id=1,
            id=1,
            reward=UpdateRewardsRequestReward(),
        )
        """
        _response = self._raw_client.update(account_id, id, reward=reward, request_options=request_options)
        return _response.data


class AsyncRewardsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRewardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRewardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRewardsClient
        """
        return self._raw_client

    async def list(
        self,
        account_id: int,
        *,
        card_id: typing.Optional[int] = None,
        active: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ListRewardsResponseItem]:
        """
        Returns all rewards for the store. Optionally filter by card or active status.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        card_id : typing.Optional[int]
            Filter rewards belonging to a specific card

        active : typing.Optional[str]
            When present, return only active rewards

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListRewardsResponseItem]
            An array of reward objects

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.rewards.list(
                account_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            account_id, card_id=card_id, active=active, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        account_id: int,
        *,
        reward: CreateRewardsRequestReward,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateRewardsResponse:
        """
        Creates a new reward for a loyalty card. The card must belong to the same store.
        The `card_id` is required on create but cannot be changed afterwards.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        reward : CreateRewardsRequestReward

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateRewardsResponse
            The newly created reward object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.rewards import CreateRewardsRequestReward

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.rewards.create(
                account_id=1,
                reward=CreateRewardsRequestReward(
                    card_id=1,
                    name="name",
                    stamps_required=1,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(account_id, reward=reward, request_options=request_options)
        return _response.data

    async def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetRewardsResponse:
        """
        Returns a single reward by ID.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Reward ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetRewardsResponse
            A reward object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.rewards.get(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(account_id, id, request_options=request_options)
        return _response.data

    async def delete(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Permanently deletes a reward. This cannot be undone.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Reward ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.rewards.delete(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(account_id, id, request_options=request_options)
        return _response.data

    async def update(
        self,
        account_id: int,
        id: int,
        *,
        reward: UpdateRewardsRequestReward,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateRewardsResponse:
        """
        Updates an existing reward. The `card_id` cannot be changed after creation.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Reward ID

        reward : UpdateRewardsRequestReward

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateRewardsResponse
            The updated reward object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.rewards import UpdateRewardsRequestReward

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.rewards.update(
                account_id=1,
                id=1,
                reward=UpdateRewardsRequestReward(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(account_id, id, reward=reward, request_options=request_options)
        return _response.data
