# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_customers_request_customer import CreateCustomersRequestCustomer
    from .create_customers_response import CreateCustomersResponse
    from .get_customers_response import GetCustomersResponse
    from .list_customers_response import ListCustomersResponse
    from .list_customers_response_pagination import ListCustomersResponsePagination
    from .update_customers_request_customer import UpdateCustomersRequestCustomer
    from .update_customers_response import UpdateCustomersResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateCustomersRequestCustomer": ".create_customers_request_customer",
    "CreateCustomersResponse": ".create_customers_response",
    "GetCustomersResponse": ".get_customers_response",
    "ListCustomersResponse": ".list_customers_response",
    "ListCustomersResponsePagination": ".list_customers_response_pagination",
    "UpdateCustomersRequestCustomer": ".update_customers_request_customer",
    "UpdateCustomersResponse": ".update_customers_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateCustomersRequestCustomer",
    "CreateCustomersResponse",
    "GetCustomersResponse",
    "ListCustomersResponse",
    "ListCustomersResponsePagination",
    "UpdateCustomersRequestCustomer",
    "UpdateCustomersResponse",
]
