# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetCustomersResponse(UniversalBaseModel):
    account_id: int = pydantic.Field()
    """
    Parent store ID
    """

    birthday: str = pydantic.Field()
    """
    Birthday as YYYY-MM-DD
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    customer_cards: typing.List[str] = pydantic.Field()
    """
    Cards this customer is enrolled on
    """

    email: str = pydantic.Field()
    """
    Email address, unique per store
    """

    external_references: typing.List[str] = pydantic.Field()
    """
    Links to records in other systems
    """

    first_name: str = pydantic.Field()
    """
    First name
    """

    id: int = pydantic.Field()
    """
    Unique customer ID
    """

    last_name: str = pydantic.Field()
    """
    Last name
    """

    metadata: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Free form per customer data
    """

    phone: str = pydantic.Field()
    """
    Phone number, unique per store
    """

    stamp_count: int = pydantic.Field()
    """
    Total stamps across every card
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
