# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListCustomersResponsePagination(UniversalBaseModel):
    count: int = pydantic.Field()
    """
    Total customers matching the query
    """

    items: int = pydantic.Field()
    """
    Customers per page
    """

    page: int = pydantic.Field()
    """
    Current page number
    """

    pages: int = pydantic.Field()
    """
    Total number of pages
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
