# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateCustomersRequestCustomer(UniversalBaseModel):
    birthday: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer's birthday (YYYY-MM-DD)
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer's email address (unique per store)
    """

    external_references: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Array of `{source, external_id, metadata}` objects to upsert
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer's first name
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer's last name
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Shallow-merged into existing metadata
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer's phone number (unique per store)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
