# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPostersClient, RawPostersClient
from .types.create_posters_request_poster import CreatePostersRequestPoster
from .types.create_posters_response import CreatePostersResponse
from .types.get_posters_response import GetPostersResponse
from .types.list_posters_response_item import ListPostersResponseItem
from .types.update_posters_request_poster import UpdatePostersRequestPoster
from .types.update_posters_response import UpdatePostersResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PostersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPostersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPostersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPostersClient
        """
        return self._raw_client

    def list(
        self,
        account_id: int,
        *,
        card_id: typing.Optional[int] = None,
        active: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ListPostersResponseItem]:
        """
        Returns all posters for the store. Optionally filter by card or active status.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        card_id : typing.Optional[int]
            Filter posters belonging to a specific card

        active : typing.Optional[str]
            When present, return only active posters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListPostersResponseItem]
            An array of poster objects

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.posters.list(
            account_id=1,
        )
        """
        _response = self._raw_client.list(account_id, card_id=card_id, active=active, request_options=request_options)
        return _response.data

    def create(
        self,
        account_id: int,
        *,
        poster: CreatePostersRequestPoster,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePostersResponse:
        """
        Creates a new printable QR code poster for customer signup. The poster will automatically
        generate a unique public signup URL and QR code. The `card_id` is required on create to
        associate the poster with a loyalty card.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        poster : CreatePostersRequestPoster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePostersResponse
            The newly created poster object

        Examples
        --------
        from leal import Leal
        from leal.posters import CreatePostersRequestPoster

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.posters.create(
            account_id=1,
            poster=CreatePostersRequestPoster(
                card_id=1,
            ),
        )
        """
        _response = self._raw_client.create(account_id, poster=poster, request_options=request_options)
        return _response.data

    def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPostersResponse:
        """
        Returns a single poster by ID, including generated signup and display URLs.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Poster ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPostersResponse
            A poster object

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.posters.get(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.get(account_id, id, request_options=request_options)
        return _response.data

    def delete(self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes a poster. The public signup URL will stop working.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Poster ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.posters.delete(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.delete(account_id, id, request_options=request_options)
        return _response.data

    def update(
        self,
        account_id: int,
        id: int,
        *,
        poster: UpdatePostersRequestPoster,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePostersResponse:
        """
        Updates an existing poster. The `card_id` cannot be changed after creation.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Poster ID

        poster : UpdatePostersRequestPoster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePostersResponse
            The updated poster object

        Examples
        --------
        from leal import Leal
        from leal.posters import UpdatePostersRequestPoster

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.posters.update(
            account_id=1,
            id=1,
            poster=UpdatePostersRequestPoster(),
        )
        """
        _response = self._raw_client.update(account_id, id, poster=poster, request_options=request_options)
        return _response.data


class AsyncPostersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPostersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPostersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPostersClient
        """
        return self._raw_client

    async def list(
        self,
        account_id: int,
        *,
        card_id: typing.Optional[int] = None,
        active: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ListPostersResponseItem]:
        """
        Returns all posters for the store. Optionally filter by card or active status.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        card_id : typing.Optional[int]
            Filter posters belonging to a specific card

        active : typing.Optional[str]
            When present, return only active posters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListPostersResponseItem]
            An array of poster objects

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.posters.list(
                account_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            account_id, card_id=card_id, active=active, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        account_id: int,
        *,
        poster: CreatePostersRequestPoster,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePostersResponse:
        """
        Creates a new printable QR code poster for customer signup. The poster will automatically
        generate a unique public signup URL and QR code. The `card_id` is required on create to
        associate the poster with a loyalty card.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        poster : CreatePostersRequestPoster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePostersResponse
            The newly created poster object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.posters import CreatePostersRequestPoster

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.posters.create(
                account_id=1,
                poster=CreatePostersRequestPoster(
                    card_id=1,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(account_id, poster=poster, request_options=request_options)
        return _response.data

    async def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPostersResponse:
        """
        Returns a single poster by ID, including generated signup and display URLs.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Poster ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPostersResponse
            A poster object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.posters.get(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(account_id, id, request_options=request_options)
        return _response.data

    async def delete(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Permanently deletes a poster. The public signup URL will stop working.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Poster ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.posters.delete(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(account_id, id, request_options=request_options)
        return _response.data

    async def update(
        self,
        account_id: int,
        id: int,
        *,
        poster: UpdatePostersRequestPoster,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePostersResponse:
        """
        Updates an existing poster. The `card_id` cannot be changed after creation.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Poster ID

        poster : UpdatePostersRequestPoster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePostersResponse
            The updated poster object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.posters import UpdatePostersRequestPoster

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.posters.update(
                account_id=1,
                id=1,
                poster=UpdatePostersRequestPoster(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(account_id, id, poster=poster, request_options=request_options)
        return _response.data
