# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_rewards_request_reward import CreateRewardsRequestReward
    from .create_rewards_response import CreateRewardsResponse
    from .get_rewards_response import GetRewardsResponse
    from .list_rewards_response_item import ListRewardsResponseItem
    from .update_rewards_request_reward import UpdateRewardsRequestReward
    from .update_rewards_response import UpdateRewardsResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateRewardsRequestReward": ".create_rewards_request_reward",
    "CreateRewardsResponse": ".create_rewards_response",
    "GetRewardsResponse": ".get_rewards_response",
    "ListRewardsResponseItem": ".list_rewards_response_item",
    "UpdateRewardsRequestReward": ".update_rewards_request_reward",
    "UpdateRewardsResponse": ".update_rewards_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateRewardsRequestReward",
    "CreateRewardsResponse",
    "GetRewardsResponse",
    "ListRewardsResponseItem",
    "UpdateRewardsRequestReward",
    "UpdateRewardsResponse",
]
