# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateRewardsRequestReward(UniversalBaseModel):
    active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the reward is active and redeemable (defaults to true)
    """

    card_id: int = pydantic.Field()
    """
    ID of the loyalty card this reward belongs to
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detailed description of the reward
    """

    name: str = pydantic.Field()
    """
    Display name of the reward (e.g. 'Free Coffee')
    """

    position: typing.Optional[int] = pydantic.Field(default=None)
    """
    Display order position (lower numbers appear first)
    """

    stamps_required: int = pydantic.Field()
    """
    Number of stamps needed to unlock this reward (must be > 0)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
