# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateRewardsRequestReward(UniversalBaseModel):
    active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the reward is active and redeemable
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detailed description of the reward
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the reward
    """

    position: typing.Optional[int] = pydantic.Field(default=None)
    """
    Display order position
    """

    stamps_required: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of stamps needed to unlock this reward (must be > 0)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
