# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateRewardsResponse(UniversalBaseModel):
    account_id: int = pydantic.Field()
    """
    Parent store ID
    """

    active: bool = pydantic.Field()
    """
    Whether the reward can currently be redeemed
    """

    card_id: int = pydantic.Field()
    """
    ID of the loyalty card this reward belongs to
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    description: str = pydantic.Field()
    """
    Longer description of the reward
    """

    id: int = pydantic.Field()
    """
    Unique reward ID
    """

    name: str = pydantic.Field()
    """
    Display name of the reward
    """

    position: int = pydantic.Field()
    """
    Display order
    """

    stamps_required: int = pydantic.Field()
    """
    Stamps needed before the reward can be redeemed
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
