# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCustomerCardsClient, RawCustomerCardsClient
from .types.get_customer_cards_response import GetCustomerCardsResponse
from .types.list_customer_cards_response_item import ListCustomerCardsResponseItem
from .types.redeem_customer_cards_response import RedeemCustomerCardsResponse
from .types.stamp_customer_cards_response import StampCustomerCardsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CustomerCardsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCustomerCardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCustomerCardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCustomerCardsClient
        """
        return self._raw_client

    def list(
        self, account_id: int, customer_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListCustomerCardsResponseItem]:
        """
        Returns all loyalty cards enrolled for a specific customer, including stamp progress,
        status, wallet pass installation state, and wallet pass URLs (`apple_wallet_url` and
        `google_wallet_url`) that you can use to let customers add their loyalty card to
        Apple Wallet or Google Wallet from your own app or website.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListCustomerCardsResponseItem]
            An array of the customer's loyalty cards

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customer_cards.list(
            account_id=1,
            customer_id=1,
        )
        """
        _response = self._raw_client.list(account_id, customer_id, request_options=request_options)
        return _response.data

    def get(
        self, account_id: int, customer_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCustomerCardsResponse:
        """
        Returns detailed information about a specific customer card, including stamp progress,
        a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
        (`apple_wallet_url` and `google_wallet_url`) for adding the card to Apple Wallet or
        Google Wallet.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        id : int
            Customer card ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCustomerCardsResponse
            A customer card, with its available rewards

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customer_cards.get(
            account_id=1,
            customer_id=1,
            id=1,
        )
        """
        _response = self._raw_client.get(account_id, customer_id, id, request_options=request_options)
        return _response.data

    def redeem(
        self,
        account_id: int,
        customer_id: int,
        id: int,
        *,
        reward_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RedeemCustomerCardsResponse:
        """
        Redeems a reward for a customer, deducting the required stamps from their card.
        The customer must have enough stamps on this card to cover the reward's cost.
        Triggers wallet pass updates and push notifications.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        id : int
            Customer card ID

        reward_id : int
            Reward ID to redeem

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RedeemCustomerCardsResponse
            The redemption that was recorded

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customer_cards.redeem(
            account_id=1,
            customer_id=1,
            id=1,
            reward_id=1,
        )
        """
        _response = self._raw_client.redeem(
            account_id, customer_id, id, reward_id=reward_id, request_options=request_options
        )
        return _response.data

    def stamp(
        self,
        account_id: int,
        customer_id: int,
        id: int,
        *,
        stamps: int,
        skip_notifications: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StampCustomerCardsResponse:
        """
        Adds stamps to a customer's loyalty card. Triggers ledger entries, wallet pass updates,
        and push notifications. Pass `skip_notifications` to stamp silently.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        id : int
            Customer card ID

        stamps : int
            Number of stamps to add (e.g. 1, 3)

        skip_notifications : typing.Optional[bool]
            When true, stamp changes bypass notifications

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StampCustomerCardsResponse
            The updated customer card, with its available rewards

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customer_cards.stamp(
            account_id=1,
            customer_id=1,
            id=1,
            stamps=1,
        )
        """
        _response = self._raw_client.stamp(
            account_id,
            customer_id,
            id,
            stamps=stamps,
            skip_notifications=skip_notifications,
            request_options=request_options,
        )
        return _response.data


class AsyncCustomerCardsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCustomerCardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCustomerCardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCustomerCardsClient
        """
        return self._raw_client

    async def list(
        self, account_id: int, customer_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListCustomerCardsResponseItem]:
        """
        Returns all loyalty cards enrolled for a specific customer, including stamp progress,
        status, wallet pass installation state, and wallet pass URLs (`apple_wallet_url` and
        `google_wallet_url`) that you can use to let customers add their loyalty card to
        Apple Wallet or Google Wallet from your own app or website.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListCustomerCardsResponseItem]
            An array of the customer's loyalty cards

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customer_cards.list(
                account_id=1,
                customer_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(account_id, customer_id, request_options=request_options)
        return _response.data

    async def get(
        self, account_id: int, customer_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCustomerCardsResponse:
        """
        Returns detailed information about a specific customer card, including stamp progress,
        a list of rewards the customer has earned enough stamps to redeem, and wallet pass URLs
        (`apple_wallet_url` and `google_wallet_url`) for adding the card to Apple Wallet or
        Google Wallet.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        id : int
            Customer card ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCustomerCardsResponse
            A customer card, with its available rewards

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customer_cards.get(
                account_id=1,
                customer_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(account_id, customer_id, id, request_options=request_options)
        return _response.data

    async def redeem(
        self,
        account_id: int,
        customer_id: int,
        id: int,
        *,
        reward_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RedeemCustomerCardsResponse:
        """
        Redeems a reward for a customer, deducting the required stamps from their card.
        The customer must have enough stamps on this card to cover the reward's cost.
        Triggers wallet pass updates and push notifications.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        id : int
            Customer card ID

        reward_id : int
            Reward ID to redeem

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RedeemCustomerCardsResponse
            The redemption that was recorded

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customer_cards.redeem(
                account_id=1,
                customer_id=1,
                id=1,
                reward_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.redeem(
            account_id, customer_id, id, reward_id=reward_id, request_options=request_options
        )
        return _response.data

    async def stamp(
        self,
        account_id: int,
        customer_id: int,
        id: int,
        *,
        stamps: int,
        skip_notifications: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StampCustomerCardsResponse:
        """
        Adds stamps to a customer's loyalty card. Triggers ledger entries, wallet pass updates,
        and push notifications. Pass `skip_notifications` to stamp silently.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer_id : int
            Customer ID

        id : int
            Customer card ID

        stamps : int
            Number of stamps to add (e.g. 1, 3)

        skip_notifications : typing.Optional[bool]
            When true, stamp changes bypass notifications

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StampCustomerCardsResponse
            The updated customer card, with its available rewards

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customer_cards.stamp(
                account_id=1,
                customer_id=1,
                id=1,
                stamps=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stamp(
            account_id,
            customer_id,
            id,
            stamps=stamps,
            skip_notifications=skip_notifications,
            request_options=request_options,
        )
        return _response.data
