# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateLocationsRequestLocation(UniversalBaseModel):
    address: str = pydantic.Field()
    """
    Full street address – automatically geocoded to lat/lng
    """

    name: str = pydantic.Field()
    """
    Location name (e.g. 'High Street Branch')
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
