# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetLocationsResponse(UniversalBaseModel):
    account_id: int = pydantic.Field()
    """
    Parent store ID
    """

    address: str = pydantic.Field()
    """
    Full street address
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    id: int = pydantic.Field()
    """
    Unique location ID
    """

    latitude: float = pydantic.Field()
    """
    Geocoded latitude (auto-derived from address)
    """

    longitude: float = pydantic.Field()
    """
    Geocoded longitude (auto-derived from address)
    """

    name: str = pydantic.Field()
    """
    Location name (e.g. 'Downtown Branch')
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
