# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawWebhookSubscriptionsClient, RawWebhookSubscriptionsClient
from .types.get_api_v1accounts_account_id_webhook_subscriptions_id_response import (
    GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse,
)
from .types.get_api_v1accounts_account_id_webhook_subscriptions_response_item import (
    GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem,
)
from .types.patch_api_v1accounts_account_id_webhook_subscriptions_id_response import (
    PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse,
)
from .types.post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret_response import (
    PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse,
)
from .types.post_api_v1accounts_account_id_webhook_subscriptions_id_test_response import (
    PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse,
)
from .types.post_api_v1accounts_account_id_webhook_subscriptions_response import (
    PostApiV1AccountsAccountIdWebhookSubscriptionsResponse,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhookSubscriptionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhookSubscriptionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhookSubscriptionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhookSubscriptionsClient
        """
        return self._raw_client

    def get_api_v1accounts_account_id_webhook_subscriptions(
        self,
        account_id: int,
        *,
        event: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem]:
        """
        Returns every webhook subscription for the store, oldest first. Signing secrets are not included; fetch a single subscription to read its secret.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        event : typing.Optional[str]
            Only return subscriptions that list this event (or `*`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem]
            An array of webhook subscriptions

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.get_api_v1accounts_account_id_webhook_subscriptions(
            account_id=1,
        )
        """
        _response = self._raw_client.get_api_v1accounts_account_id_webhook_subscriptions(
            account_id, event=event, request_options=request_options
        )
        return _response.data

    def post_api_v1accounts_account_id_webhook_subscriptions(
        self,
        account_id: int,
        *,
        target_url: str,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        event: typing.Optional[str] = OMIT,
        events: typing.Optional[typing.Sequence[str]] = OMIT,
        payload_format: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostApiV1AccountsAccountIdWebhookSubscriptionsResponse:
        """
        Subscribes a URL to one or more events. The response includes the signing `secret`; store it to
        verify deliveries. The URL must be publicly reachable over https.

        Events: `customer.created`, `customer.updated`, `customer_card.created`, `stamp.earned`, `stamp.removed`, `reward.unlocked`, `reward.redeemed`, or `*` for all of them.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        target_url : str
            Public https URL that will receive the POST requests

        description : typing.Optional[str]
            Your own label, up to 255 characters

        enabled : typing.Optional[bool]
            Create the subscription disabled by passing false (defaults to true)

        event : typing.Optional[str]
            A single event to subscribe to. Same as `events` with one entry

        events : typing.Optional[typing.Sequence[str]]
            Events to subscribe to, or `["*"]` for every event. Required unless `event` is given

        payload_format : typing.Optional[str]
            `envelope` (default) or `flat`. `flat` sends the bare data object and cannot be combined with `*`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostApiV1AccountsAccountIdWebhookSubscriptionsResponse
            The new webhook subscription, with its secret

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.post_api_v1accounts_account_id_webhook_subscriptions(
            account_id=1,
            target_url="target_url",
        )
        """
        _response = self._raw_client.post_api_v1accounts_account_id_webhook_subscriptions(
            account_id,
            target_url=target_url,
            description=description,
            enabled=enabled,
            event=event,
            events=events,
            payload_format=payload_format,
            request_options=request_options,
        )
        return _response.data

    def get_api_v1accounts_account_id_webhook_subscriptions_id(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse:
        """
        Returns a single subscription, including its signing secret and the result of the most recent delivery.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse
            A webhook subscription, with its secret

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.get_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.get_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id, id, request_options=request_options
        )
        return _response.data

    def delete_api_v1accounts_account_id_webhook_subscriptions_id(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Stops deliveries and deletes the subscription. This cannot be undone.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.delete_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.delete_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id, id, request_options=request_options
        )
        return _response.data

    def patch_api_v1accounts_account_id_webhook_subscriptions_id(
        self,
        account_id: int,
        id: int,
        *,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        event: typing.Optional[str] = OMIT,
        events: typing.Optional[typing.Sequence[str]] = OMIT,
        payload_format: typing.Optional[str] = OMIT,
        target_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse:
        """
        Changes the URL, events, label or payload format, or turns the subscription off and on. Re-enabling a subscription that was disabled for failing clears its failure state.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        description : typing.Optional[str]
            Your own label, up to 255 characters

        enabled : typing.Optional[bool]
            false to pause deliveries, true to resume them

        event : typing.Optional[str]
            A single event. Same as `events` with one entry

        events : typing.Optional[typing.Sequence[str]]
            Replaces the list of events, or `["*"]` for every event

        payload_format : typing.Optional[str]
            `envelope` or `flat`

        target_url : typing.Optional[str]
            Public https URL that will receive the POST requests

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse
            The updated webhook subscription

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.patch_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.patch_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id,
            id,
            description=description,
            enabled=enabled,
            event=event,
            events=events,
            payload_format=payload_format,
            target_url=target_url,
            request_options=request_options,
        )
        return _response.data

    def post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse:
        """
        Replaces the subscription's signing secret. Deliveries are signed with the new secret straight away, so update your receiver at the same time.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse
            The webhook subscription, with its new secret

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret(
            account_id, id, request_options=request_options
        )
        return _response.data

    def post_api_v1accounts_account_id_webhook_subscriptions_id_test(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse:
        """
        Immediately sends a signed `webhook.test` event to the subscription's URL and reports what
        happened, so you can check your endpoint and signature verification without waiting for real
        activity. Test events are not retried and do not count towards disabling the subscription.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse
            The outcome of the test delivery

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.webhook_subscriptions.post_api_v1accounts_account_id_webhook_subscriptions_id_test(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.post_api_v1accounts_account_id_webhook_subscriptions_id_test(
            account_id, id, request_options=request_options
        )
        return _response.data


class AsyncWebhookSubscriptionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhookSubscriptionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhookSubscriptionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhookSubscriptionsClient
        """
        return self._raw_client

    async def get_api_v1accounts_account_id_webhook_subscriptions(
        self,
        account_id: int,
        *,
        event: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem]:
        """
        Returns every webhook subscription for the store, oldest first. Signing secrets are not included; fetch a single subscription to read its secret.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        event : typing.Optional[str]
            Only return subscriptions that list this event (or `*`)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem]
            An array of webhook subscriptions

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.get_api_v1accounts_account_id_webhook_subscriptions(
                account_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_api_v1accounts_account_id_webhook_subscriptions(
            account_id, event=event, request_options=request_options
        )
        return _response.data

    async def post_api_v1accounts_account_id_webhook_subscriptions(
        self,
        account_id: int,
        *,
        target_url: str,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        event: typing.Optional[str] = OMIT,
        events: typing.Optional[typing.Sequence[str]] = OMIT,
        payload_format: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostApiV1AccountsAccountIdWebhookSubscriptionsResponse:
        """
        Subscribes a URL to one or more events. The response includes the signing `secret`; store it to
        verify deliveries. The URL must be publicly reachable over https.

        Events: `customer.created`, `customer.updated`, `customer_card.created`, `stamp.earned`, `stamp.removed`, `reward.unlocked`, `reward.redeemed`, or `*` for all of them.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        target_url : str
            Public https URL that will receive the POST requests

        description : typing.Optional[str]
            Your own label, up to 255 characters

        enabled : typing.Optional[bool]
            Create the subscription disabled by passing false (defaults to true)

        event : typing.Optional[str]
            A single event to subscribe to. Same as `events` with one entry

        events : typing.Optional[typing.Sequence[str]]
            Events to subscribe to, or `["*"]` for every event. Required unless `event` is given

        payload_format : typing.Optional[str]
            `envelope` (default) or `flat`. `flat` sends the bare data object and cannot be combined with `*`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostApiV1AccountsAccountIdWebhookSubscriptionsResponse
            The new webhook subscription, with its secret

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.post_api_v1accounts_account_id_webhook_subscriptions(
                account_id=1,
                target_url="target_url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_api_v1accounts_account_id_webhook_subscriptions(
            account_id,
            target_url=target_url,
            description=description,
            enabled=enabled,
            event=event,
            events=events,
            payload_format=payload_format,
            request_options=request_options,
        )
        return _response.data

    async def get_api_v1accounts_account_id_webhook_subscriptions_id(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse:
        """
        Returns a single subscription, including its signing secret and the result of the most recent delivery.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse
            A webhook subscription, with its secret

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.get_api_v1accounts_account_id_webhook_subscriptions_id(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id, id, request_options=request_options
        )
        return _response.data

    async def delete_api_v1accounts_account_id_webhook_subscriptions_id(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Stops deliveries and deletes the subscription. This cannot be undone.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.delete_api_v1accounts_account_id_webhook_subscriptions_id(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id, id, request_options=request_options
        )
        return _response.data

    async def patch_api_v1accounts_account_id_webhook_subscriptions_id(
        self,
        account_id: int,
        id: int,
        *,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        event: typing.Optional[str] = OMIT,
        events: typing.Optional[typing.Sequence[str]] = OMIT,
        payload_format: typing.Optional[str] = OMIT,
        target_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse:
        """
        Changes the URL, events, label or payload format, or turns the subscription off and on. Re-enabling a subscription that was disabled for failing clears its failure state.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        description : typing.Optional[str]
            Your own label, up to 255 characters

        enabled : typing.Optional[bool]
            false to pause deliveries, true to resume them

        event : typing.Optional[str]
            A single event. Same as `events` with one entry

        events : typing.Optional[typing.Sequence[str]]
            Replaces the list of events, or `["*"]` for every event

        payload_format : typing.Optional[str]
            `envelope` or `flat`

        target_url : typing.Optional[str]
            Public https URL that will receive the POST requests

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse
            The updated webhook subscription

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.patch_api_v1accounts_account_id_webhook_subscriptions_id(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch_api_v1accounts_account_id_webhook_subscriptions_id(
            account_id,
            id,
            description=description,
            enabled=enabled,
            event=event,
            events=events,
            payload_format=payload_format,
            target_url=target_url,
            request_options=request_options,
        )
        return _response.data

    async def post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse:
        """
        Replaces the subscription's signing secret. Deliveries are signed with the new secret straight away, so update your receiver at the same time.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse
            The webhook subscription, with its new secret

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret(
            account_id, id, request_options=request_options
        )
        return _response.data

    async def post_api_v1accounts_account_id_webhook_subscriptions_id_test(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse:
        """
        Immediately sends a signed `webhook.test` event to the subscription's URL and reports what
        happened, so you can check your endpoint and signature verification without waiting for real
        activity. Test events are not retried and do not count towards disabling the subscription.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Webhook subscription ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse
            The outcome of the test delivery

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webhook_subscriptions.post_api_v1accounts_account_id_webhook_subscriptions_id_test(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_api_v1accounts_account_id_webhook_subscriptions_id_test(
            account_id, id, request_options=request_options
        )
        return _response.data
