# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCustomersClient, RawCustomersClient
from .types.create_customers_request_customer import CreateCustomersRequestCustomer
from .types.create_customers_response import CreateCustomersResponse
from .types.get_customers_response import GetCustomersResponse
from .types.list_customers_response import ListCustomersResponse
from .types.update_customers_request_customer import UpdateCustomersRequestCustomer
from .types.update_customers_response import UpdateCustomersResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CustomersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCustomersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCustomersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCustomersClient
        """
        return self._raw_client

    def list(
        self,
        account_id: int,
        *,
        search: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        items: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomersResponse:
        """
        Returns a paginated list of customers for the store. Use the `search` parameter to filter
        by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
        `source` AND `external_id` together to perform an exact lookup by an external reference -
        the response will contain at most one customer.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        search : typing.Optional[str]
            Search query to filter customers by name, email, phone, card code (barcode), or external reference ID

        source : typing.Optional[str]
            External system slug (e.g. `square`, `shopify`). When combined with `external_id`, performs an exact lookup.

        external_id : typing.Optional[str]
            External system's identifier for the customer. Must be combined with `source`.

        page : typing.Optional[int]
            Page number (defaults to 1)

        items : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomersResponse
            A page of customers, with pagination metadata

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customers.list(
            account_id=1,
        )
        """
        _response = self._raw_client.list(
            account_id,
            search=search,
            source=source,
            external_id=external_id,
            page=page,
            items=items,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        account_id: int,
        *,
        customer: CreateCustomersRequestCustomer,
        card_id: typing.Optional[int] = OMIT,
        send_card_links: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCustomersResponse:
        """
        Creates a new customer for the store. Requires `first_name` and at least one of `email` or `phone`.
        Optionally enroll the customer in a loyalty card by passing `card_id`, and trigger delivery of
        card links (email/SMS) by passing `send_card_links`. When a card with initial stamps is assigned,
        those stamps are automatically applied as a welcome bonus.

        Pass `metadata` to attach arbitrary key/value data, and `external_references` to link the
        customer to records in other systems (e.g. Square, Shopify). External references are upserted
        by `(source, external_id)` so this endpoint is safe to call with the same references twice.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer : CreateCustomersRequestCustomer

        card_id : typing.Optional[int]
            Loyalty card ID to auto-enroll the customer in

        send_card_links : typing.Optional[bool]
            When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes `apple_wallet_url` and `google_wallet_url` in each customer card object so you can deliver them yourself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCustomersResponse
            The newly created customer. Includes a customer_card object when card_id was supplied.

        Examples
        --------
        from leal import Leal
        from leal.customers import CreateCustomersRequestCustomer

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customers.create(
            account_id=1,
            customer=CreateCustomersRequestCustomer(
                first_name="first_name",
            ),
        )
        """
        _response = self._raw_client.create(
            account_id,
            customer=customer,
            card_id=card_id,
            send_card_links=send_card_links,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCustomersResponse:
        """
        Returns detailed information about a single customer, including all of their
        enrolled loyalty cards with stamp progress and wallet pass URLs (`apple_wallet_url`
        and `google_wallet_url`) for each card. Also includes `metadata` and
        `external_references` so you can sync state with external systems.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCustomersResponse
            A customer, including their enrolled loyalty cards

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customers.get(
            account_id=1,
            id=1,
        )
        """
        _response = self._raw_client.get(account_id, id, request_options=request_options)
        return _response.data

    def update(
        self,
        account_id: int,
        id: int,
        *,
        customer: UpdateCustomersRequestCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCustomersResponse:
        """
        Updates an existing customer's details. To add stamps or redeem rewards, use the
        customer cards endpoints instead.

        `metadata` is shallow-merged into the existing metadata. `external_references` are upserted
        by `(source, external_id)` - to remove a reference, omit it from subsequent calls and use
        a separate `DELETE` workflow (not yet exposed via API; manage in dashboard for now).

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        customer : UpdateCustomersRequestCustomer

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCustomersResponse
            The updated customer

        Examples
        --------
        from leal import Leal
        from leal.customers import UpdateCustomersRequestCustomer

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.customers.update(
            account_id=1,
            id=1,
            customer=UpdateCustomersRequestCustomer(),
        )
        """
        _response = self._raw_client.update(account_id, id, customer=customer, request_options=request_options)
        return _response.data


class AsyncCustomersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCustomersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCustomersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCustomersClient
        """
        return self._raw_client

    async def list(
        self,
        account_id: int,
        *,
        search: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        items: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomersResponse:
        """
        Returns a paginated list of customers for the store. Use the `search` parameter to filter
        by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
        `source` AND `external_id` together to perform an exact lookup by an external reference -
        the response will contain at most one customer.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        search : typing.Optional[str]
            Search query to filter customers by name, email, phone, card code (barcode), or external reference ID

        source : typing.Optional[str]
            External system slug (e.g. `square`, `shopify`). When combined with `external_id`, performs an exact lookup.

        external_id : typing.Optional[str]
            External system's identifier for the customer. Must be combined with `source`.

        page : typing.Optional[int]
            Page number (defaults to 1)

        items : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomersResponse
            A page of customers, with pagination metadata

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.list(
                account_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            account_id,
            search=search,
            source=source,
            external_id=external_id,
            page=page,
            items=items,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        account_id: int,
        *,
        customer: CreateCustomersRequestCustomer,
        card_id: typing.Optional[int] = OMIT,
        send_card_links: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCustomersResponse:
        """
        Creates a new customer for the store. Requires `first_name` and at least one of `email` or `phone`.
        Optionally enroll the customer in a loyalty card by passing `card_id`, and trigger delivery of
        card links (email/SMS) by passing `send_card_links`. When a card with initial stamps is assigned,
        those stamps are automatically applied as a welcome bonus.

        Pass `metadata` to attach arbitrary key/value data, and `external_references` to link the
        customer to records in other systems (e.g. Square, Shopify). External references are upserted
        by `(source, external_id)` so this endpoint is safe to call with the same references twice.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer : CreateCustomersRequestCustomer

        card_id : typing.Optional[int]
            Loyalty card ID to auto-enroll the customer in

        send_card_links : typing.Optional[bool]
            When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes `apple_wallet_url` and `google_wallet_url` in each customer card object so you can deliver them yourself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCustomersResponse
            The newly created customer. Includes a customer_card object when card_id was supplied.

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.customers import CreateCustomersRequestCustomer

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.create(
                account_id=1,
                customer=CreateCustomersRequestCustomer(
                    first_name="first_name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            account_id,
            customer=customer,
            card_id=card_id,
            send_card_links=send_card_links,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCustomersResponse:
        """
        Returns detailed information about a single customer, including all of their
        enrolled loyalty cards with stamp progress and wallet pass URLs (`apple_wallet_url`
        and `google_wallet_url`) for each card. Also includes `metadata` and
        `external_references` so you can sync state with external systems.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCustomersResponse
            A customer, including their enrolled loyalty cards

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.get(
                account_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(account_id, id, request_options=request_options)
        return _response.data

    async def update(
        self,
        account_id: int,
        id: int,
        *,
        customer: UpdateCustomersRequestCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCustomersResponse:
        """
        Updates an existing customer's details. To add stamps or redeem rewards, use the
        customer cards endpoints instead.

        `metadata` is shallow-merged into the existing metadata. `external_references` are upserted
        by `(source, external_id)` - to remove a reference, omit it from subsequent calls and use
        a separate `DELETE` workflow (not yet exposed via API; manage in dashboard for now).

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        customer : UpdateCustomersRequestCustomer

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCustomersResponse
            The updated customer

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.customers import UpdateCustomersRequestCustomer

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.update(
                account_id=1,
                id=1,
                customer=UpdateCustomersRequestCustomer(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(account_id, id, customer=customer, request_options=request_options)
        return _response.data
