# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.gone_error import GoneError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error import Error
from .types.create_customers_request_customer import CreateCustomersRequestCustomer
from .types.create_customers_response import CreateCustomersResponse
from .types.get_customers_response import GetCustomersResponse
from .types.list_customers_response import ListCustomersResponse
from .types.update_customers_request_customer import UpdateCustomersRequestCustomer
from .types.update_customers_response import UpdateCustomersResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCustomersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        account_id: int,
        *,
        search: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        items: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListCustomersResponse]:
        """
        Returns a paginated list of customers for the store. Use the `search` parameter to filter
        by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
        `source` AND `external_id` together to perform an exact lookup by an external reference -
        the response will contain at most one customer.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        search : typing.Optional[str]
            Search query to filter customers by name, email, phone, card code (barcode), or external reference ID

        source : typing.Optional[str]
            External system slug (e.g. `square`, `shopify`). When combined with `external_id`, performs an exact lookup.

        external_id : typing.Optional[str]
            External system's identifier for the customer. Must be combined with `source`.

        page : typing.Optional[int]
            Page number (defaults to 1)

        items : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListCustomersResponse]
            A page of customers, with pagination metadata
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers",
            method="GET",
            params={
                "search": search,
                "source": source,
                "external_id": external_id,
                "page": page,
                "items": items,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListCustomersResponse,
                    parse_obj_as(
                        type_=ListCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        account_id: int,
        *,
        customer: CreateCustomersRequestCustomer,
        card_id: typing.Optional[int] = OMIT,
        send_card_links: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateCustomersResponse]:
        """
        Creates a new customer for the store. Requires `first_name` and at least one of `email` or `phone`.
        Optionally enroll the customer in a loyalty card by passing `card_id`, and trigger delivery of
        card links (email/SMS) by passing `send_card_links`. When a card with initial stamps is assigned,
        those stamps are automatically applied as a welcome bonus.

        Pass `metadata` to attach arbitrary key/value data, and `external_references` to link the
        customer to records in other systems (e.g. Square, Shopify). External references are upserted
        by `(source, external_id)` so this endpoint is safe to call with the same references twice.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer : CreateCustomersRequestCustomer

        card_id : typing.Optional[int]
            Loyalty card ID to auto-enroll the customer in

        send_card_links : typing.Optional[bool]
            When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes `apple_wallet_url` and `google_wallet_url` in each customer card object so you can deliver them yourself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateCustomersResponse]
            The newly created customer. Includes a customer_card object when card_id was supplied.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers",
            method="POST",
            json={
                "card_id": card_id,
                "customer": convert_and_respect_annotation_metadata(
                    object_=customer, annotation=CreateCustomersRequestCustomer, direction="write"
                ),
                "send_card_links": send_card_links,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateCustomersResponse,
                    parse_obj_as(
                        type_=CreateCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetCustomersResponse]:
        """
        Returns detailed information about a single customer, including all of their
        enrolled loyalty cards with stamp progress and wallet pass URLs (`apple_wallet_url`
        and `google_wallet_url`) for each card. Also includes `metadata` and
        `external_references` so you can sync state with external systems.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetCustomersResponse]
            A customer, including their enrolled loyalty cards
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetCustomersResponse,
                    parse_obj_as(
                        type_=GetCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        account_id: int,
        id: int,
        *,
        customer: UpdateCustomersRequestCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateCustomersResponse]:
        """
        Updates an existing customer's details. To add stamps or redeem rewards, use the
        customer cards endpoints instead.

        `metadata` is shallow-merged into the existing metadata. `external_references` are upserted
        by `(source, external_id)` - to remove a reference, omit it from subsequent calls and use
        a separate `DELETE` workflow (not yet exposed via API; manage in dashboard for now).

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        customer : UpdateCustomersRequestCustomer

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateCustomersResponse]
            The updated customer
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers/{encode_path_param(id)}",
            method="PATCH",
            json={
                "customer": convert_and_respect_annotation_metadata(
                    object_=customer, annotation=UpdateCustomersRequestCustomer, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateCustomersResponse,
                    parse_obj_as(
                        type_=UpdateCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCustomersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        account_id: int,
        *,
        search: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        items: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListCustomersResponse]:
        """
        Returns a paginated list of customers for the store. Use the `search` parameter to filter
        by name, email, phone, card code (barcode), or external reference ID. Alternatively, pass
        `source` AND `external_id` together to perform an exact lookup by an external reference -
        the response will contain at most one customer.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        search : typing.Optional[str]
            Search query to filter customers by name, email, phone, card code (barcode), or external reference ID

        source : typing.Optional[str]
            External system slug (e.g. `square`, `shopify`). When combined with `external_id`, performs an exact lookup.

        external_id : typing.Optional[str]
            External system's identifier for the customer. Must be combined with `source`.

        page : typing.Optional[int]
            Page number (defaults to 1)

        items : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListCustomersResponse]
            A page of customers, with pagination metadata
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers",
            method="GET",
            params={
                "search": search,
                "source": source,
                "external_id": external_id,
                "page": page,
                "items": items,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListCustomersResponse,
                    parse_obj_as(
                        type_=ListCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        account_id: int,
        *,
        customer: CreateCustomersRequestCustomer,
        card_id: typing.Optional[int] = OMIT,
        send_card_links: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateCustomersResponse]:
        """
        Creates a new customer for the store. Requires `first_name` and at least one of `email` or `phone`.
        Optionally enroll the customer in a loyalty card by passing `card_id`, and trigger delivery of
        card links (email/SMS) by passing `send_card_links`. When a card with initial stamps is assigned,
        those stamps are automatically applied as a welcome bonus.

        Pass `metadata` to attach arbitrary key/value data, and `external_references` to link the
        customer to records in other systems (e.g. Square, Shopify). External references are upserted
        by `(source, external_id)` so this endpoint is safe to call with the same references twice.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        customer : CreateCustomersRequestCustomer

        card_id : typing.Optional[int]
            Loyalty card ID to auto-enroll the customer in

        send_card_links : typing.Optional[bool]
            When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes `apple_wallet_url` and `google_wallet_url` in each customer card object so you can deliver them yourself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateCustomersResponse]
            The newly created customer. Includes a customer_card object when card_id was supplied.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers",
            method="POST",
            json={
                "card_id": card_id,
                "customer": convert_and_respect_annotation_metadata(
                    object_=customer, annotation=CreateCustomersRequestCustomer, direction="write"
                ),
                "send_card_links": send_card_links,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateCustomersResponse,
                    parse_obj_as(
                        type_=CreateCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, account_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetCustomersResponse]:
        """
        Returns detailed information about a single customer, including all of their
        enrolled loyalty cards with stamp progress and wallet pass URLs (`apple_wallet_url`
        and `google_wallet_url`) for each card. Also includes `metadata` and
        `external_references` so you can sync state with external systems.

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetCustomersResponse]
            A customer, including their enrolled loyalty cards
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetCustomersResponse,
                    parse_obj_as(
                        type_=GetCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        account_id: int,
        id: int,
        *,
        customer: UpdateCustomersRequestCustomer,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateCustomersResponse]:
        """
        Updates an existing customer's details. To add stamps or redeem rewards, use the
        customer cards endpoints instead.

        `metadata` is shallow-merged into the existing metadata. `external_references` are upserted
        by `(source, external_id)` - to remove a reference, omit it from subsequent calls and use
        a separate `DELETE` workflow (not yet exposed via API; manage in dashboard for now).

        Parameters
        ----------
        account_id : int
            Store (account) ID

        id : int
            Customer ID

        customer : UpdateCustomersRequestCustomer

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateCustomersResponse]
            The updated customer
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/accounts/{encode_path_param(account_id)}/customers/{encode_path_param(id)}",
            method="PATCH",
            json={
                "customer": convert_and_respect_annotation_metadata(
                    object_=customer, annotation=UpdateCustomersRequestCustomer, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateCustomersResponse,
                    parse_obj_as(
                        type_=UpdateCustomersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 410:
                raise GoneError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
