# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_api_v1accounts_account_id_webhook_subscriptions_id_response import (
        GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse,
    )
    from .get_api_v1accounts_account_id_webhook_subscriptions_response_item import (
        GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem,
    )
    from .patch_api_v1accounts_account_id_webhook_subscriptions_id_response import (
        PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse,
    )
    from .post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret_response import (
        PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse,
    )
    from .post_api_v1accounts_account_id_webhook_subscriptions_id_test_response import (
        PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse,
    )
    from .post_api_v1accounts_account_id_webhook_subscriptions_response import (
        PostApiV1AccountsAccountIdWebhookSubscriptionsResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse": ".get_api_v1accounts_account_id_webhook_subscriptions_id_response",
    "GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem": ".get_api_v1accounts_account_id_webhook_subscriptions_response_item",
    "PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse": ".patch_api_v1accounts_account_id_webhook_subscriptions_id_response",
    "PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse": ".post_api_v1accounts_account_id_webhook_subscriptions_id_rotate_secret_response",
    "PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse": ".post_api_v1accounts_account_id_webhook_subscriptions_id_test_response",
    "PostApiV1AccountsAccountIdWebhookSubscriptionsResponse": ".post_api_v1accounts_account_id_webhook_subscriptions_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse",
    "GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem",
    "PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse",
    "PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse",
    "PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse",
    "PostApiV1AccountsAccountIdWebhookSubscriptionsResponse",
]
