# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse(UniversalBaseModel):
    account_id: int = pydantic.Field()
    """
    Parent store ID
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    description: str = pydantic.Field()
    """
    Your own label for the subscription
    """

    disabled_at: str = pydantic.Field()
    """
    ISO 8601 time the subscription was disabled
    """

    disabled_reason: str = pydantic.Field()
    """
    `disabled_by_user`, `failing` or `blocked_address`
    """

    enabled: bool = pydantic.Field()
    """
    Whether events are being delivered
    """

    event: str = pydantic.Field()
    """
    The event, when there is exactly one (kept for older integrations)
    """

    events: typing.List[str] = pydantic.Field()
    """
    Events delivered to this URL, or `["*"]` for every event
    """

    id: int = pydantic.Field()
    """
    Unique subscription ID
    """

    last_delivery_at: str = pydantic.Field()
    """
    ISO 8601 time of the most recent delivery attempt
    """

    last_delivery_error: str = pydantic.Field()
    """
    Why the most recent attempt failed
    """

    last_delivery_status: float = pydantic.Field()
    """
    HTTP status your URL returned on the most recent attempt
    """

    payload_format: str = pydantic.Field()
    """
    `envelope` (default) or `flat` (the bare data object, used by Zapier)
    """

    secret: str = pydantic.Field()
    """
    Signing secret (`whsec_...`). Use it to verify the `webhook-signature` header.
    """

    target_url: str = pydantic.Field()
    """
    URL that receives the POST requests
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
