# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse(UniversalBaseModel):
    delivered: bool = pydantic.Field()
    """
    True when your URL responded with a 2xx status
    """

    error: str = pydantic.Field()
    """
    Why the delivery failed
    """

    event_id: str = pydantic.Field()
    """
    The `webhook-id` of the test event
    """

    status: float = pydantic.Field()
    """
    HTTP status your URL returned
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
