# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawStoresClient, RawStoresClient
from .types.get_stores_response import GetStoresResponse
from .types.list_stores_response_item import ListStoresResponseItem
from .types.update_stores_request_account import UpdateStoresRequestAccount
from .types.update_stores_response import UpdateStoresResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StoresClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStoresClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[ListStoresResponseItem]:
        """
        Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListStoresResponseItem]
            An array of store objects

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.stores.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def get(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> GetStoresResponse:
        """
        Returns detailed information for a single store, including summary counts for its associated resources.

        Parameters
        ----------
        id : int
            Store ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetStoresResponse
            A store object

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.stores.get(
            id=1,
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self, id: int, *, account: UpdateStoresRequestAccount, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateStoresResponse:
        """
        Updates the store's name or store_name. Use `store_name` for the public-facing name displayed to customers.

        Parameters
        ----------
        id : int
            Store ID

        account : UpdateStoresRequestAccount

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateStoresResponse
            The updated store object

        Examples
        --------
        from leal import Leal
        from leal.stores import UpdateStoresRequestAccount

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.stores.update(
            id=1,
            account=UpdateStoresRequestAccount(),
        )
        """
        _response = self._raw_client.update(id, account=account, request_options=request_options)
        return _response.data


class AsyncStoresClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStoresClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListStoresResponseItem]:
        """
        Returns every store the authenticated user has access to, including summary counts for locations, cards, customers, and posters.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListStoresResponseItem]
            An array of store objects

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.stores.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def get(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> GetStoresResponse:
        """
        Returns detailed information for a single store, including summary counts for its associated resources.

        Parameters
        ----------
        id : int
            Store ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetStoresResponse
            A store object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.stores.get(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self, id: int, *, account: UpdateStoresRequestAccount, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateStoresResponse:
        """
        Updates the store's name or store_name. Use `store_name` for the public-facing name displayed to customers.

        Parameters
        ----------
        id : int
            Store ID

        account : UpdateStoresRequestAccount

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateStoresResponse
            The updated store object

        Examples
        --------
        import asyncio

        from leal import AsyncLeal
        from leal.stores import UpdateStoresRequestAccount

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.stores.update(
                id=1,
                account=UpdateStoresRequestAccount(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, account=account, request_options=request_options)
        return _response.data
