# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_posters_request_poster import CreatePostersRequestPoster
    from .create_posters_response import CreatePostersResponse
    from .get_posters_response import GetPostersResponse
    from .list_posters_response_item import ListPostersResponseItem
    from .update_posters_request_poster import UpdatePostersRequestPoster
    from .update_posters_response import UpdatePostersResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreatePostersRequestPoster": ".create_posters_request_poster",
    "CreatePostersResponse": ".create_posters_response",
    "GetPostersResponse": ".get_posters_response",
    "ListPostersResponseItem": ".list_posters_response_item",
    "UpdatePostersRequestPoster": ".update_posters_request_poster",
    "UpdatePostersResponse": ".update_posters_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreatePostersRequestPoster",
    "CreatePostersResponse",
    "GetPostersResponse",
    "ListPostersResponseItem",
    "UpdatePostersRequestPoster",
    "UpdatePostersResponse",
]
