# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreatePostersResponse(UniversalBaseModel):
    account_id: int = pydantic.Field()
    """
    Parent store ID
    """

    active: bool = pydantic.Field()
    """
    Whether the public signup URL is live
    """

    card_id: int = pydantic.Field()
    """
    Loyalty card customers are signed up to
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    display_url: str = pydantic.Field()
    """
    URL of the on screen version of the poster
    """

    id: int = pydantic.Field()
    """
    Unique poster ID
    """

    paper_size: str = pydantic.Field()
    """
    Paper size the poster is laid out for
    """

    primary_color: str = pydantic.Field()
    """
    Hex colour for the poster background
    """

    qr_code_url: str = pydantic.Field()
    """
    URL encoded in the QR code
    """

    secondary_color: str = pydantic.Field()
    """
    Hex accent colour
    """

    signup_url: str = pydantic.Field()
    """
    Public URL the QR code points at
    """

    text_color: str = pydantic.Field()
    """
    Hex colour for poster text
    """

    title: str = pydantic.Field()
    """
    Heading printed on the poster
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
