# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreatePostersRequestPoster(UniversalBaseModel):
    active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the poster is active (defaults to true)
    """

    card_id: int = pydantic.Field()
    """
    ID of the loyalty card this poster links to
    """

    paper_size: typing.Optional[str] = pydantic.Field(default=None)
    """
    Print size – one of: a4, a5, a6, letter
    """

    primary_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary brand color as a hex string (e.g. '#FF5733')
    """

    secondary_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Secondary brand color as a hex string
    """

    text_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text color as a hex string
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Headline text displayed on the poster
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
