# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdatePostersRequestPoster(UniversalBaseModel):
    active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the poster is active
    """

    contact_collection_mode: typing.Optional[str] = pydantic.Field(default=None)
    """
    Which contact fields appear on the public signup form
    """

    minimum_age: typing.Optional[float] = pydantic.Field(default=None)
    """
    Minimum customer age required for signup. Requires require_birthday to be true.
    """

    paper_size: typing.Optional[str] = pydantic.Field(default=None)
    """
    Print size – one of: a4, a5, a6, letter
    """

    primary_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary brand color as a hex string
    """

    require_birthday: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether date of birth is required on the public signup form
    """

    require_email: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether email is required when it is collected
    """

    require_phone: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether phone number is required when it is collected
    """

    secondary_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Secondary brand color as a hex string
    """

    text_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text color as a hex string
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Headline text displayed on the poster
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
