# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateStoresResponse(UniversalBaseModel):
    cards_count: int = pydantic.Field()
    """
    Number of loyalty card templates
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    customers_count: int = pydantic.Field()
    """
    Number of enrolled customers
    """

    display_store_name: str = pydantic.Field()
    """
    Resolved display name (store_name if present, otherwise name)
    """

    id: int = pydantic.Field()
    """
    Unique store ID
    """

    locations_count: int = pydantic.Field()
    """
    Number of physical locations
    """

    name: str = pydantic.Field()
    """
    Internal account name
    """

    personal: bool = pydantic.Field()
    """
    Whether this is the user's personal account
    """

    posters_count: int = pydantic.Field()
    """
    Number of QR signup posters
    """

    store_name: str = pydantic.Field()
    """
    Public-facing store name
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
