# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .check_status_response_rate_limit import CheckStatusResponseRateLimit


class CheckStatusResponse(UniversalBaseModel):
    api_version: str = pydantic.Field()
    """
    Current API version
    """

    authentication: str = pydantic.Field()
    """
    How to authenticate a request
    """

    developer_portal_url: str = pydantic.Field()
    """
    Developer portal: quickstart, auth, webhooks
    """

    documentation_url: str = pydantic.Field()
    """
    Human readable API reference
    """

    openapi_url: str = pydantic.Field()
    """
    OpenAPI description of this API
    """

    rate_limit: CheckStatusResponseRateLimit
    status: str = pydantic.Field()
    """
    'ok' while the API is serving requests
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
