# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckStatusResponseVersioning(UniversalBaseModel):
    current: str = pydantic.Field()
    """
    The version to build against
    """

    deprecated: typing.List[str] = pydantic.Field()
    """
    Versions that are deprecated but still serving
    """

    policy_url: str = pydantic.Field()
    """
    The published versioning and deprecation policy
    """

    signalling: str = pydantic.Field()
    """
    The headers a deprecated version sends
    """

    supported: typing.List[str] = pydantic.Field()
    """
    Every version still serving requests
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
