# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckStatusResponseRateLimit(UniversalBaseModel):
    limit: int = pydantic.Field()
    """
    Requests allowed per window
    """

    scope: str = pydantic.Field()
    """
    What the limit is counted against
    """

    window_seconds: int = pydantic.Field()
    """
    Length of the window in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
