# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateCardsRequestCard(UniversalBaseModel):
    card_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex colour for the card background (e.g. '#6B4226')
    """

    header_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional header text displayed on the card
    """

    initial_stamps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of stamps pre-filled on new customer cards (must be >= 0 and < stamps_required)
    """

    name: str = pydantic.Field()
    """
    Card name (e.g. 'Coffee Loyalty Card')
    """

    stamp_background_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex colour for stamp backgrounds
    """

    stamp_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex colour for stamp icons
    """

    stamp_icon: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stamp icon identifier
    """

    stamps_required: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of stamps needed to complete the card (1–21)
    """

    strip_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex colour for the strip (used when strip_type is 'color')
    """

    strip_preset: typing.Optional[str] = pydantic.Field(default=None)
    """
    Preset strip image identifier (used when strip_type is 'preset')
    """

    strip_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Strip image type
    """

    text_color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex colour for card text
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
