# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateCardsResponse(UniversalBaseModel):
    archived_at: str = pydantic.Field()
    """
    ISO 8601 timestamp when the card was archived, or null if active
    """

    auxiliary_fields: typing.List[str] = pydantic.Field()
    """
    Up to two extra front-of-pass fields
    """

    card_color: str = pydantic.Field()
    """
    Hex colour for the card background (e.g. '#6B4226')
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    customer_cards_count: int = pydantic.Field()
    """
    Number of customer card instances issued
    """

    expires_at: str = pydantic.Field()
    """
    ISO 8601 timestamp when the card expires, or null if it does not expire
    """

    header_text: str = pydantic.Field()
    """
    Optional header text displayed on the card
    """

    id: int = pydantic.Field()
    """
    Unique card ID
    """

    initial_stamps: int = pydantic.Field()
    """
    Number of stamps pre-filled on new customer cards (0 to stamps_required - 1)
    """

    name: str = pydantic.Field()
    """
    Card name (e.g. 'Coffee Loyalty Card')
    """

    rewards_count: int = pydantic.Field()
    """
    Number of rewards defined for this card
    """

    show_member_field: bool = pydantic.Field()
    """
    Whether wallet passes show the member name field
    """

    show_stamps_to_reward_field: bool = pydantic.Field()
    """
    Whether wallet passes show the stamps-to-reward field
    """

    stamp_background_color: str = pydantic.Field()
    """
    Hex colour for stamp backgrounds
    """

    stamp_color: str = pydantic.Field()
    """
    Hex colour for stamp icons
    """

    stamp_icon: str = pydantic.Field()
    """
    Icon used for stamps (e.g. 'coffee', 'heart', 'star')
    """

    stamps_required: int = pydantic.Field()
    """
    Number of stamps needed to complete the card (1–21)
    """

    strip_color: str = pydantic.Field()
    """
    Hex colour for the strip (when strip_type is 'color')
    """

    strip_preset: str = pydantic.Field()
    """
    Preset strip image identifier (when strip_type is 'preset')
    """

    strip_type: str = pydantic.Field()
    """
    Strip image type: 'color', 'image', or 'preset'
    """

    text_color: str = pydantic.Field()
    """
    Hex colour for card text
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
