# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import Error, ErrorErrors
    from .errors import GoneError, NotFoundError, TooManyRequestsError, UnauthorizedError, UnprocessableEntityError
    from . import cards, customer_cards, customers, locations, posters, rewards, status, stores
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .cards import (
        CreateCardsRequestCard,
        CreateCardsResponse,
        GetCardsResponse,
        ListCardsResponseItem,
        UpdateCardsRequestCard,
        UpdateCardsResponse,
    )
    from .client import AsyncLeal, Leal
    from .customer_cards import (
        GetCustomerCardsResponse,
        ListCustomerCardsResponseItem,
        RedeemCustomerCardsResponse,
        RedeemCustomerCardsResponseRedemption,
        StampCustomerCardsResponse,
    )
    from .customers import (
        CreateCustomersRequestCustomer,
        CreateCustomersResponse,
        GetCustomersResponse,
        ListCustomersResponse,
        ListCustomersResponsePagination,
        UpdateCustomersRequestCustomer,
        UpdateCustomersResponse,
    )
    from .environment import LealEnvironment
    from .locations import (
        CreateLocationsRequestLocation,
        CreateLocationsResponse,
        GetLocationsResponse,
        ListLocationsResponseItem,
        UpdateLocationsRequestLocation,
        UpdateLocationsResponse,
    )
    from .posters import (
        CreatePostersRequestPoster,
        CreatePostersResponse,
        GetPostersResponse,
        ListPostersResponseItem,
        UpdatePostersRequestPoster,
        UpdatePostersResponse,
    )
    from .rewards import (
        CreateRewardsRequestReward,
        CreateRewardsResponse,
        GetRewardsResponse,
        ListRewardsResponseItem,
        UpdateRewardsRequestReward,
        UpdateRewardsResponse,
    )
    from .status import CheckStatusResponse, CheckStatusResponseRateLimit, CheckStatusResponseVersioning
    from .stores import GetStoresResponse, ListStoresResponseItem, UpdateStoresRequestAccount, UpdateStoresResponse
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncLeal": ".client",
    "CheckStatusResponse": ".status",
    "CheckStatusResponseRateLimit": ".status",
    "CheckStatusResponseVersioning": ".status",
    "CreateCardsRequestCard": ".cards",
    "CreateCardsResponse": ".cards",
    "CreateCustomersRequestCustomer": ".customers",
    "CreateCustomersResponse": ".customers",
    "CreateLocationsRequestLocation": ".locations",
    "CreateLocationsResponse": ".locations",
    "CreatePostersRequestPoster": ".posters",
    "CreatePostersResponse": ".posters",
    "CreateRewardsRequestReward": ".rewards",
    "CreateRewardsResponse": ".rewards",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "Error": ".types",
    "ErrorErrors": ".types",
    "GetCardsResponse": ".cards",
    "GetCustomerCardsResponse": ".customer_cards",
    "GetCustomersResponse": ".customers",
    "GetLocationsResponse": ".locations",
    "GetPostersResponse": ".posters",
    "GetRewardsResponse": ".rewards",
    "GetStoresResponse": ".stores",
    "GoneError": ".errors",
    "Leal": ".client",
    "LealEnvironment": ".environment",
    "ListCardsResponseItem": ".cards",
    "ListCustomerCardsResponseItem": ".customer_cards",
    "ListCustomersResponse": ".customers",
    "ListCustomersResponsePagination": ".customers",
    "ListLocationsResponseItem": ".locations",
    "ListPostersResponseItem": ".posters",
    "ListRewardsResponseItem": ".rewards",
    "ListStoresResponseItem": ".stores",
    "NotFoundError": ".errors",
    "RedeemCustomerCardsResponse": ".customer_cards",
    "RedeemCustomerCardsResponseRedemption": ".customer_cards",
    "StampCustomerCardsResponse": ".customer_cards",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "UpdateCardsRequestCard": ".cards",
    "UpdateCardsResponse": ".cards",
    "UpdateCustomersRequestCustomer": ".customers",
    "UpdateCustomersResponse": ".customers",
    "UpdateLocationsRequestLocation": ".locations",
    "UpdateLocationsResponse": ".locations",
    "UpdatePostersRequestPoster": ".posters",
    "UpdatePostersResponse": ".posters",
    "UpdateRewardsRequestReward": ".rewards",
    "UpdateRewardsResponse": ".rewards",
    "UpdateStoresRequestAccount": ".stores",
    "UpdateStoresResponse": ".stores",
    "__version__": ".version",
    "cards": ".cards",
    "customer_cards": ".customer_cards",
    "customers": ".customers",
    "locations": ".locations",
    "posters": ".posters",
    "rewards": ".rewards",
    "status": ".status",
    "stores": ".stores",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncLeal",
    "CheckStatusResponse",
    "CheckStatusResponseRateLimit",
    "CheckStatusResponseVersioning",
    "CreateCardsRequestCard",
    "CreateCardsResponse",
    "CreateCustomersRequestCustomer",
    "CreateCustomersResponse",
    "CreateLocationsRequestLocation",
    "CreateLocationsResponse",
    "CreatePostersRequestPoster",
    "CreatePostersResponse",
    "CreateRewardsRequestReward",
    "CreateRewardsResponse",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "Error",
    "ErrorErrors",
    "GetCardsResponse",
    "GetCustomerCardsResponse",
    "GetCustomersResponse",
    "GetLocationsResponse",
    "GetPostersResponse",
    "GetRewardsResponse",
    "GetStoresResponse",
    "GoneError",
    "Leal",
    "LealEnvironment",
    "ListCardsResponseItem",
    "ListCustomerCardsResponseItem",
    "ListCustomersResponse",
    "ListCustomersResponsePagination",
    "ListLocationsResponseItem",
    "ListPostersResponseItem",
    "ListRewardsResponseItem",
    "ListStoresResponseItem",
    "NotFoundError",
    "RedeemCustomerCardsResponse",
    "RedeemCustomerCardsResponseRedemption",
    "StampCustomerCardsResponse",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "UpdateCardsRequestCard",
    "UpdateCardsResponse",
    "UpdateCustomersRequestCustomer",
    "UpdateCustomersResponse",
    "UpdateLocationsRequestLocation",
    "UpdateLocationsResponse",
    "UpdatePostersRequestPoster",
    "UpdatePostersResponse",
    "UpdateRewardsRequestReward",
    "UpdateRewardsResponse",
    "UpdateStoresRequestAccount",
    "UpdateStoresResponse",
    "__version__",
    "cards",
    "customer_cards",
    "customers",
    "locations",
    "posters",
    "rewards",
    "status",
    "stores",
]
