# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class ListCustomerCardsResponseItem(UniversalBaseModel):
    apple_wallet_url: str = pydantic.Field()
    """
    Link to add or view the pass in Apple Wallet
    """

    card_id: int = pydantic.Field()
    """
    Loyalty card template ID
    """

    card_name: str = pydantic.Field()
    """
    Name of the loyalty card
    """

    created_at: str = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    google_wallet_url: str = pydantic.Field()
    """
    Link to add or view the pass in Google Wallet
    """

    id: int = pydantic.Field()
    """
    Customer card ID
    """

    issued_at: str = pydantic.Field()
    """
    ISO 8601 timestamp the card was issued
    """

    pass_installed: bool = pydantic.Field()
    """
    Whether the wallet pass has been installed
    """

    progress_percentage: float = pydantic.Field()
    """
    Completion towards the next reward, 0 to 100
    """

    stamps_count: int = pydantic.Field()
    """
    Stamps collected so far
    """

    stamps_remaining: int = pydantic.Field()
    """
    Stamps still needed to complete the card
    """

    status: str = pydantic.Field()
    """
    Current state of the customer card
    """

    updated_at: str = pydantic.Field()
    """
    ISO 8601 last-update timestamp
    """

    uuid_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="uuid"),
        pydantic.Field(alias="uuid", description="Public identifier used in wallet pass URLs"),
    ]
    """
    Public identifier used in wallet pass URLs
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
