# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .redeem_customer_cards_response_redemption import RedeemCustomerCardsResponseRedemption


class RedeemCustomerCardsResponse(UniversalBaseModel):
    redemption: RedeemCustomerCardsResponseRedemption
    success: bool = pydantic.Field()
    """
    True when the reward was redeemed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
