# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RedeemCustomerCardsResponseRedemption(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Redemption ID
    """

    redeemed_at: str = pydantic.Field()
    """
    ISO 8601 timestamp of the redemption
    """

    reward_id: int = pydantic.Field()
    """
    Reward that was redeemed
    """

    reward_name: str = pydantic.Field()
    """
    Display name of the reward
    """

    stamps_remaining: int = pydantic.Field()
    """
    Stamps left on the card afterwards
    """

    stamps_spent: int = pydantic.Field()
    """
    Stamps deducted from the card
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
