# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawStatusClient, RawStatusClient
from .types.check_status_response import CheckStatusResponse


class StatusClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStatusClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStatusClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStatusClient
        """
        return self._raw_client

    def check(self, *, request_options: typing.Optional[RequestOptions] = None) -> CheckStatusResponse:
        """
        Returns the status of the API. No authentication required.

        Every response from this API, including this one, carries `RateLimit-Limit`,
        `RateLimit-Remaining`, `RateLimit-Reset` and `RateLimit-Policy`. Exceeding
        the limit returns 429 with `Retry-After` in seconds.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckStatusResponse
            The service status

        Examples
        --------
        from leal import Leal

        client = Leal(
            token="YOUR_TOKEN",
        )
        client.status.check()
        """
        _response = self._raw_client.check(request_options=request_options)
        return _response.data


class AsyncStatusClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStatusClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStatusClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStatusClient
        """
        return self._raw_client

    async def check(self, *, request_options: typing.Optional[RequestOptions] = None) -> CheckStatusResponse:
        """
        Returns the status of the API. No authentication required.

        Every response from this API, including this one, carries `RateLimit-Limit`,
        `RateLimit-Remaining`, `RateLimit-Reset` and `RateLimit-Policy`. Exceeding
        the limit returns 429 with `Retry-After` in seconds.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckStatusResponse
            The service status

        Examples
        --------
        import asyncio

        from leal import AsyncLeal

        client = AsyncLeal(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.status.check()


        asyncio.run(main())
        """
        _response = await self._raw_client.check(request_options=request_options)
        return _response.data
